version: 2

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
  test:
    working_directory: ~/circleci-python
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run: sudo pip install pytest numpy
      - run: pytest tests

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
