version: 2
jobs:
  test:
    working_directory: ~/circleci-python
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run: sudo pip install pytest numpy
      - run: pytest tests
